name: Push to Space
on: workflow_dispatch

env:
  SPACE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  
jobs:
  push-to-space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Deta Space CLI & set SPACE_ACCESS_TOKEN environment variable
        shell: bash
        run: |
          curl -fsSL https://get.deta.dev/space-cli.sh | sh
          echo '/home/runner/.detaspace/bin' >> $GITHUB_PATH
          space link --id $PROJECT_ID
          space push
